//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserLoginSessions = new HashSet<UserLoginSession>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastFailedAttempt { get; set; }
        public int FailedAttempts { get; set; }
        public int Status { get; set; }
        public int SourceType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string OtherState { get; set; }
        public Nullable<int> CityID { get; set; }
        public string OtherCity { get; set; }
        public string ZipCode { get; set; }
        public string Website { get; set; }
        public int RoleID { get; set; }
        public string ProfilePicture { get; set; }
        public byte[] Password { get; set; }
        public int RegisterVia { get; set; }
        public string RegistrationIP { get; set; }
        public bool ResetPassword { get; set; }
        public string PasswordResetCode { get; set; }
        public string FacbookUserID { get; set; }
        public decimal TotalEarning { get; set; }
    
        public virtual ICollection<UserLoginSession> UserLoginSessions { get; set; }
    }
}
